### ISSUE TITLE
Hint for capitalizing first letter of words via CSS

### ISSUE THREAD

**Issue by S0AndS0** [Youpinadi/cssfizzbuzz#3]
Excellent implementation of Fizzbuzz! I did notice though that ya can use...

```CSS
li::first-letter {
  text-transform: uppercase;
}
```

... to capitalize the first letter of each output word, this would enable `fizz` and `buzz` to be joined via `::before` and `::after` elements without camel-casing.

For completeness I purpose that CSS be similar to...

```CSS
ol {
  list-style-position: inside;
}

li:nth-child(3),
li:nth-child(5) {
  list-style: none;
}

li:nth-child(3n)::before {
  content: "fizz";
}

li:nth-child(5n)::after {
  content: "buzz";
}

li::first-letter {
  text-transform: uppercase;
}
```

If ya add an Open Source license to this repository I'll be happy to submit a Pull Request with these changes.
